In [5]:
import pandas as pd
# pandas got 2 types : Series, and Data Frame 
# pandas series is an enhanced array one size
grades = pd.Series([80,85,90,95], index=["A","B","C","D"])
print(grades)
print("\n=== data manipulation ===")
print(grades["B"])
print(grades["D"])

print("Add value to Pandas Series")
grades["E"] = 100
print(grades)

print("Delete Specific index")
grades = grades.drop("B")
print(grades)

print("Descriptive statistics")
print("Count: ", grades.count())
print("Min: ", grades.min())
print("Max:: ", grades.max())
print("Mean: ", grades.mean())
print("Std: ", grades.std())

print("Descriptive statistics")
print(grades.describe())


A    80
B    85
C    90
D    95
dtype: int64

=== data manipulation ===
85
95
Add value to Pandas Series
A     80
B     85
C     90
D     95
E    100
dtype: int64
Delete Specific index
A     80
C     90
D     95
E    100
dtype: int64
Descriptive statistics
Count:  4
Min:  80
Max::  100
Mean:  91.25
Std:  8.539125638299666
Descriptive statistics
count      4.000000
mean      91.250000
std        8.539126
min       80.000000
25%       87.500000
50%       92.500000
75%       96.250000
max      100.000000
dtype: float64


In [9]:
# numpy is n-dimensional array
# from numpy you can create 1, 2 n-dimensional array
import numpy as np
array1 = np.array([10, 20, 30, 40, 50])

print(array1)
print(array1[3])
# add new value to numpy array
array1 = np.append(array1, 60)
print(array1)
# delete specific index
array1 = np.delete(array1, 2)
print(array1)

[10 20 30 40 50]
40
[10 20 30 40 50 60]
[10 20 40 50 60]


In [ ]:
array2 = np.array([
    [1,2,3,4,5],
    [10,20,30,40,50],
    [100,200,300,400,500]
])

print("sum: ", array2.sum()) #* sum of all numbers in array
print("min: ", array2.min()) #* lowest number in the array
print("max: ", array2.max()) #* highest number 
print("mean: ", array2.mean()) #* average from the sum of array
print("std: ", array2.std())  #* how spread out the numbers are from an axis

sum:  1665
min:  1
max:  500
mean:  111.0
std:  157.21323099535866
