In [ ]:
import numpy as np 
import pandas as pd 
# Convert Independent variables to Polynomial Features
# Polynomial Math following degree
from sklearn.preprocessing import PolynomialFeatures
#?  PolynomialFeatures converts one input variable into powers:
#?  X becomes [1, X, X², X³, X⁴].
from sklearn.linear_model import LinearRegression
#? LinearRegression will learn the relationship between the polynomial features and electricity consumption.

# * step 1: load data set from CSV file
dataset = pd.read_csv("electricity.csv")
print(dataset)

# * step 2: select independent variable (input)
#  "People" contains the number of people living in each house.
# The double brackets keep X in a two-dimensional format.
X = dataset[["People"]].values
# * step 3: select dependent variable (output)
# Consumption_kwh is the value the model will learn to predict
Y = dataset["Consumption_kwh"].values

# * step 4: create polynomial features up to degree 4
# The model will use:
# 1, X, X², X³, and X⁴
#
# Example:
# If X = 2, the features become [1, 2, 4, 8, 16].
polynomial_features = PolynomialFeatures(degree=4)

# Convert the original People values into polynomial features.
# fit_transform() learns the feature structure and transforms X. 
X_poly = polynomial_features.fit_transform(X)
# ? display polynomial feature table
print("==== Polynomial Features ====")
print(X_poly)

# * step 5: create and train Polynomial Regression Model
# train the model using polynomial input data and the actual electricity consumption values.
polynomial_model = LinearRegression()
polynomial_model.fit(X_poly, Y)
# * step 6:  Create the value we want to predict 
# we want to predict electricity consumption for 12 people 
# The value is written as [[12]] because Scikit-learn expects input data in two-dimensional format.
position = np.array([[12]])
# Convert 12 into the same polynomial format used during training:
# [1, 12, 12², 12³, 12⁴]
position_poly = polynomial_features.transform(position)

# * step 7: Use the trained model to make the prediction.
position_predict = polynomial_model.predict(position_poly)
# display predicted electricity consumption
print("Electricity consumption of 12 people", position_predict[0], "Kwh")

   People  Consumption_kwh
0       1              120
1       2              180
2       3              260
3       4              380
4       5              530
5       6              720
6       7              950
7       8             1230
8       9             1580
9      10             2000
==== Polynomial Features ====
[[1.000e+00 1.000e+00 1.000e+00 1.000e+00 1.000e+00]
 [1.000e+00 2.000e+00 4.000e+00 8.000e+00 1.600e+01]
 [1.000e+00 3.000e+00 9.000e+00 2.700e+01 8.100e+01]
 [1.000e+00 4.000e+00 1.600e+01 6.400e+01 2.560e+02]
 [1.000e+00 5.000e+00 2.500e+01 1.250e+02 6.250e+02]
 [1.000e+00 6.000e+00 3.600e+01 2.160e+02 1.296e+03]
 [1.000e+00 7.000e+00 4.900e+01 3.430e+02 2.401e+03]
 [1.000e+00 8.000e+00 6.400e+01 5.120e+02 4.096e+03]
 [1.000e+00 9.000e+00 8.100e+01 7.290e+02 6.561e+03]
 [1.000e+00 1.000e+01 1.000e+02 1.000e+03 1.000e+04]]
Electricity consumption of 12 people 3130.1515151515136 Kwh
