In [8]:
import numpy as np # deal array one or two dimensions
import pandas as pd # import data and virtual as table
import matplotlib.pyplot as plt # vitual data as graph

# Convert Independent variables to Polynomial Features
# Polynomial Math following degree
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression

#step 2: load data and virtual data in the table 
dataset = pd.read_csv("salary.csv");
print(dataset);

#step 3: data preprocessing or data engineering
#input or independence variable
X = dataset[["Level"]].values;
#output or dependent variable
Y = dataset["Salary"].values;

#step 4: covert input variable to polynomial Features
polynomial_features = PolynomialFeatures(degree=4)
#transform X = [1,X,x^2, X^3, X^4] to give curve line
#fit -> polynomial learn x
#transform 0> convert input variable to polynomial math
X_poly = polynomial_features.fit_transform(X);
print("==== Polynomial Features ====");
print(X_poly);

#step 5: create and train Polynomial Regression Model
polynomial_model = LinearRegression();
polynomial_model.fit(X_poly, Y);

#Step 6: predict salary for level = 6.5
position = np.array([[6.5]])
#convert 6.5 to polynomial features
position_poly = polynomial_features.transform(position);
#conevrt 6.5 exprience level, how much he got
position_predict = polynomial_model.predict(position_poly);
print("6.5 level of Expererience", position_predict[0], "$");

            Position  Level   Salary
0   Business Analyst      1    45000
1  Junior Consultant      2    50000
2  Senior Consultant      3    60000
3            Manager      4    80000
4    Country Manager      5   110000
5      Regin Manager      6   150000
6            Partner      7   200000
7     Senior Partner      8   300000
8            C-Level      9   500000
9                CEO     10  1000000
==== Polynomial Features ====
[[1.000e+00 1.000e+00 1.000e+00 1.000e+00 1.000e+00]
 [1.000e+00 2.000e+00 4.000e+00 8.000e+00 1.600e+01]
 [1.000e+00 3.000e+00 9.000e+00 2.700e+01 8.100e+01]
 [1.000e+00 4.000e+00 1.600e+01 6.400e+01 2.560e+02]
 [1.000e+00 5.000e+00 2.500e+01 1.250e+02 6.250e+02]
 [1.000e+00 6.000e+00 3.600e+01 2.160e+02 1.296e+03]
 [1.000e+00 7.000e+00 4.900e+01 3.430e+02 2.401e+03]
 [1.000e+00 8.000e+00 6.400e+01 5.120e+02 4.096e+03]
 [1.000e+00 9.000e+00 8.100e+01 7.290e+02 6.561e+03]
 [1.000e+00 1.000e+01 1.000e+02 1.000e+03 1.000e+04]]
6.5 level of Expererience 158862